# Generated by Django 4.2.15 on 2025-03-28 11:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Paypal', 'Paypal'), ('SSLCommerz', 'SSLCommerz')], default='Cash', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('adminnote', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=5)),
                ('full_name', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('home_city', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
