# Generated by Django 4.2.15 on 2025-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated_at',
            new_name='update_date',
        ),
    ]
